// front-end/src/features/devCharts/components/PeriodicCharts.tsx
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  Filler
} from 'chart.js';
import { Line } from 'react-chartjs-2';
import type { PeriodicUserMetricsDto } from '@core/models/dashboard';

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  Filler
);

interface PeriodicChartsProps {
  granularityData: PeriodicUserMetricsDto[];
}

export function PeriodicCharts({ granularityData }: PeriodicChartsProps) {
  const options = {
    responsive: true,
    plugins: {
      legend: {
        position: 'top' as const,
        labels: { color: '#94a3b8' }
      },
    },
    scales: {
      x: { grid: { color: '#334155' }, ticks: { color: '#94a3b8' } },
      y: { grid: { color: '#334155' }, ticks: { color: '#94a3b8' } },
    },
  };

  const labels = granularityData.map((item) => item.label);
  const issuesStarted = granularityData.map((item) => item.numberOfIssueStarted);
  const issuesDone = granularityData.map((item) => item.numberOfIssueDone);

  const data = {
    labels,
    datasets: [
      {
        label: 'Tickets Commencés',
        data: issuesStarted,
        borderColor: '#3b82f6',
        backgroundColor: 'rgba(59, 130, 246, 0.1)',
        fill: true,
        tension: 0.3,
      },
      {
        label: 'Tickets Terminés',
        data: issuesDone,
        borderColor: '#10b981',
        backgroundColor: 'rgba(16, 185, 129, 0.1)',
        fill: true,
        tension: 0.3,
      },
    ],
  };

  return (
    <div className="bg-slate-900 p-6 rounded-xl border border-slate-800 max-w-4xl mx-auto">
      <h2 className="text-xl font-bold text-white mb-4">Flux des Tickets (Issues Flow)</h2>
      <Line options={options} data={data} />
    </div>
  );
}

// front-end-angular/src/app/features/metrics/components/periodic-charts.component.ts
import {Component, computed, input} from '@angular/core';
import {BaseChartDirective} from 'ng2-charts';
import {Chart, ChartConfiguration, registerables} from 'chart.js';
import {UserMetrics} from '../models/userMetrics.model';

Chart.register(...registerables);

@Component({
  selector: 'app-periodic-charts',
  standalone: true,
  imports: [BaseChartDirective],
  templateUrl: './periodic-charts.component.html'
})
export class PeriodicChartsComponent {
  readonly userMetrics = input.required<UserMetrics>();

  readonly commonOptions: ChartConfiguration<'bar'>['options'] = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        position: 'bottom',
        labels: {color: '#cbd5e1', boxWidth: 12, font: {size: 11}}
      }
    },
    scales: {
      x: {grid: {color: '#334155'}, ticks: {color: '#94a3b8', font: {size: 10}}},
      y: {grid: {color: '#334155'}, ticks: {color: '#94a3b8', font: {size: 10}}}
    }
  };

  readonly doughnutOptions: ChartConfiguration<'doughnut'>['options'] = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        position: 'bottom',
        labels: {color: '#cbd5e1', boxWidth: 12, font: {size: 11}}
      }
    }
  };

  readonly issuesData = computed<ChartConfiguration<'bar'>['data']>(() => {
    const periodicMetrics = this.userMetrics().userMetricsByGranularity;
    return {
      labels: periodicMetrics.map(periodicMetric => periodicMetric.label),
      datasets: [
        {userMetrics: periodicMetrics.map(periodicMetric => periodicMetric.numberOfIssueStarted), label: 'Started', backgroundColor: 'rgba(59, 130, 246, 0.8)', borderRadius: 4},
        {userMetrics: periodicMetrics.map(periodicMetric => periodicMetric.numberOfIssueDone), label: 'Done', backgroundColor: 'rgba(16, 185, 129, 0.8)', borderRadius: 4}
      ]
    };
  });

  readonly reviewsData = computed<ChartConfiguration<'bar'>['data']>(() => {
    const periodicMetrics = this.userMetrics().userMetricsByGranularity;
    return {
      labels: periodicMetrics.map(periodicMetric => periodicMetric.label),
      datasets: [
        {userMetrics: periodicMetrics.map(periodicMetric => periodicMetric.numberOfReviewDone), label: 'Done', backgroundColor: 'rgba(139, 92, 246, 0.8)', borderRadius: 4},
        {userMetrics: periodicMetrics.map(periodicMetric => periodicMetric.numberOfReviewReopened), label: 'Reopened', backgroundColor: 'rgba(239, 68, 68, 0.8)', borderRadius: 4}
      ]
    };
  });

  readonly ratesData = computed<ChartConfiguration<'bar'>['data']>(() => {
    const periodicMetrics = this.userMetrics().userMetricsByGranularity;
    return {
      labels: periodicMetrics.map(periodicMetric => periodicMetric.label),
      datasets: [
        {userMetrics: periodicMetrics.map(periodicMetric => periodicMetric.deliverySuccessRate), label: 'Delivery %', backgroundColor: 'rgba(234, 179, 8, 0.8)', borderRadius: 4},
        {userMetrics: periodicMetrics.map(periodicMetric => periodicMetric.teamReviewParticipationRate), label: 'Review %', backgroundColor: 'rgba(236, 72, 153, 0.8)', borderRadius: 4}
      ]
    };
  });

  readonly typeDistributionData = computed<ChartConfiguration<'doughnut'>['data']>(() => {
    const data = this.userMetrics();

    const distribution = data?.issueRateByType || [];

    return {
      labels: distribution.map(item => item.type),
      datasets: [
        {
          userMetrics: distribution.map(item => item.rate),
          backgroundColor: [
            'rgba(59, 130, 246, 0.8)',
            'rgba(16, 185, 129, 0.8)',
            'rgba(239, 68, 68, 0.8)',
            'rgba(234, 179, 8, 0.8)',
            'rgba(139, 92, 246, 0.8)'
          ],
          borderWidth: 1,
          borderColor: '#1e293b'
        }
      ]
    };
  });
}

<div class="grid grid-cols-1 lg:grid-cols-3 gap-6">

  <div class="bg-slate-800/40 border border-slate-800 rounded-2xl p-5 flex flex-col">
    <h3 class="text-sm font-semibold text-white mb-4 flex items-center gap-2">
      <span class="text-blue-500">■</span> Issues Flow
    </h3>
    <div class="relative h-64 w-full mt-auto">
      <canvas baseChart [data]="issuesData()" [options]="commonOptions" type="bar"></canvas>
    </div>
  </div>

  <div class="bg-slate-800/40 border border-slate-800 rounded-2xl p-5 flex flex-col">
    <h3 class="text-sm font-semibold text-white mb-4 flex items-center gap-2">
      <span class="text-purple-500">■</span> Code Reviews
    </h3>
    <div class="relative h-64 w-full mt-auto">
      <canvas baseChart [data]="reviewsData()" [options]="commonOptions" type="bar"></canvas>
    </div>
  </div>

  <div class="bg-slate-800/40 border border-slate-800 rounded-2xl p-5 flex flex-col">
    <h3 class="text-sm font-semibold text-white mb-4 flex items-center gap-2">
      <span class="text-purple-500">■</span> Performance Rates
    </h3>
    <div class="relative h-64 w-full mt-auto">
      <canvas baseChart [data]="ratesData()" [options]="commonOptions" type="bar"></canvas>
    </div>
  </div>

  <div class="bg-slate-800/40 border border-slate-800 rounded-2xl p-5 flex flex-col">
    <h3 class="text-sm font-semibold text-white mb-4 flex items-center gap-2">
      <span class="text-red-500">■</span> Issue Type Distribution (Last Period)
    </h3>
    <div class="relative h-64 w-full mt-auto">
      <canvas baseChart [data]="typeDistributionData()" [options]="doughnutOptions" type="doughnut"></canvas>
    </div>
  </div>

</div>
