// front-end/src/features/history/components/HistoryList.tsx
import {format, parseISO} from 'date-fns';
import type {UserHistoryEventDto} from '@core/models/history';
import type {Page} from '@core/models/pages';
import {useTranslation} from "@core/hooks/useTranslation";

export function HistoryList({
                                historyPage,
                                onPageChange,
                            }: {
    historyPage: Page<UserHistoryEventDto>;
    onPageChange: (newPage: number) => void;
}) {
    const content = historyPage.content || [];
    const t = useTranslation();

    const pageMetadata = historyPage?.page || {totalPages: 0, number: 0, totalElements: 0, size: 10};
    const {totalPages, number, totalElements} = pageMetadata;

    return (
        <div className="bg-slate-900 p-6 rounded-xl border border-slate-800 mx-auto space-y-4">
            <h2 className="text-xl font-bold text-white">{t.history.title}</h2>

            {content.length === 0 ? (
                <div className="text-center py-8 text-slate-500">
                    <p>{t.history.noEvents}</p>
                </div>
            ) : (
                <div className="overflow-x-auto">
                    <table className="w-full text-left border-collapse text-sm text-slate-300">
                        <thead>
                            <tr className="border-b border-slate-800 text-slate-400 font-medium">
                                <th className="py-3 px-4">{t.issue.name}</th>
                                <th className="py-3 px-4">{t.issue.title}</th>
                                <th className="py-3 px-4">{t.issue.author}</th>
                                <th className="py-3 px-4">{t.issue.modificationDate}</th>
                                <th className="py-3 px-4">{t.issue.date}</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-500/50">
                            {content.map((event) => (
                                <tr key={event.issueKey} className="hover:bg-slate-950/40 transition-colors">
                                    <td className="py-3 px-4 font-mono text-blue-400">{event.issueKey}</td>
                                    <td className="py-3 px-4 font-mono text-blue-200">{event.issueSummary}</td>
                                    <td className="py-3 px-4 flex items-center gap-3">
                                        <img
                                            src={event.issueAssignee?.avatarUrl}
                                            alt={event.issueAssignee?.name || 'None'}
                                            className="w-9 h-9 rounded-full border border-purple-500 object-cover shrink-0"
                                        />
                                        <div className="flex flex-col">
                                            <div className="font-medium text-slate-200">{event.issueAssignee?.name || 'None'}</div>
                                            <div className="text-xs text-slate-500">{event.issueAssignee?.email || 'None'}</div>
                                        </div>
                                    </td>
                                    <td className="py-3 px-4">
                                        <span className="text-slate-400 font-medium">{event.transitionType}</span>
                                    </td>
                                    <td className="py-3 px-4 text-xs text-slate-400">
                                        {event.date ? format(parseISO(event.date), 'dd/MM/yyyy HH:mm') : '—'}
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            )}

            {totalPages > 1 && (
                <div className="flex items-center justify-between border-t border-slate-800 pt-4 text-xs text-slate-400">
                    <div>
                        {t.page.name}
                        <span className="font-bold text-slate-200">{number + 1}</span>
                        {t.page.on} {' '}
                        <span className="font-bold text-slate-200">{totalPages}</span>
                        <span className="mx-2 text-slate-700">|</span>
                        {t.page.total} : {totalElements}
                    </div>
                    <div className="flex space-x-2">
                        <button
                            onClick={() => onPageChange(number - 1)}
                            disabled={number === 0}
                            className="bg-slate-950 border border-slate-800 rounded px-3 py-1.5 hover:bg-slate-800 transition-colors disabled:opacity-30 disabled:hover:bg-slate-950"
                        >
                            {t.page.previous}
                        </button>
                        <button
                            onClick={() => onPageChange(number + 1)}
                            disabled={number === totalPages - 1}
                            className="bg-slate-950 border border-slate-800 rounded px-3 py-1.5 hover:bg-slate-800 transition-colors disabled:opacity-30 disabled:hover:bg-slate-950"
                        >
                            {t.page.next}
                        </button>
                    </div>
                </div>
            )}
        </div>
    );
}

// front-end/src/app/features/history/components/history-list.component.ts
import { Component, input, output } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-history-list',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './history-list.component.html'
})
export class HistoryListComponent {
  readonly data = input<any>();

  readonly pageChange = output<number>();
  readonly sizeChange = output<number>();

  onPageChange(newPage: number): void {
    this.pageChange.emit(newPage);
  }

  onSizeChange(event: Event): void {
    const selectElement = event.target as HTMLSelectElement;
    const newSize = Number(selectElement.value);

    this.sizeChange.emit(newSize);

    this.pageChange.emit(0);
  }
}

@if (data(); as historyPage) {
  <div class="bg-slate-800/40 border border-slate-800 rounded-2xl p-6">
    <h2 class="text-lg font-bold text-white mb-4 flex items-center gap-2">
      <span class="text-sm text-emerald-400">■</span> Recent History Logs
    </h2>

    <div class="max-w-3xl mx-auto">
      <ul class="relative border-l-2 border-slate-700 ml-3 space-y-8">

        @for (history of historyPage.content; track $index) {
          <li class="pl-8 relative">
            <div class="absolute w-4 h-4 bg-blue-500 rounded-full -left-[9px] top-1.5 ring-4 ring-slate-900"></div>

            <div class="bg-slate-800/40 border border-slate-700 rounded-xl p-5 shadow-sm hover:bg-slate-800/60 hover:border-slate-600 transition-all duration-200">

              <div class="flex flex-wrap items-start justify-between gap-3 mb-3">
                <time class="text-xs font-mono text-slate-400 mt-1">
                  {{ history.date | date:'MMM d, y, h:mm a' }}
                </time>

                <div class="flex gap-2">
                  <span class="px-2.5 py-1 rounded-md text-[10px] font-bold uppercase tracking-wider border"
                        [ngClass]="{
                          'bg-red-500/10 text-red-400 border-red-500/20': history.issueType === 'Bug' || history.issueType === 'Defect',
                          'bg-blue-500/10 text-blue-400 border-blue-500/20': history.issueType === 'Story' || history.issueType === 'Task',
                          'bg-slate-700 text-slate-300 border-slate-600': history.issueType !== 'Bug' && history.issueType !== 'Defect' && history.issueType !== 'Story' && history.issueType !== 'Task'
                        }">
                    {{ history.issueType }}
                  </span>

                  <span class="px-2.5 py-1 rounded-md text-[10px] font-bold uppercase tracking-wider border"
                        [ngClass]="{
                          'bg-emerald-500/10 text-emerald-400 border-emerald-500/20': history.transitionType === 'Done' || history.transitionType === 'Closed',
                          'bg-purple-500/10 text-purple-400 border-purple-500/20': history.transitionType === 'In Progress' || history.transitionType === 'In Review',
                          'bg-slate-700 text-slate-300 border-slate-600': history.transitionType !== 'Done' && history.transitionType !== 'Closed' && history.transitionType !== 'In Progress' && history.transitionType !== 'In Review'
                        }">
                    {{ history.transitionType }}
                  </span>
                </div>
              </div>

              <h4 class="text-slate-200 font-medium text-sm mb-4 leading-relaxed">
                <span class="text-blue-400 font-bold mr-2 hover:underline cursor-pointer">{{ history.issueKey }}</span>
                {{ history.issueSummary }}
              </h4>

              <div class="flex items-center gap-3 mt-4 pt-4 border-t border-slate-700/50">
                <div class="w-8 h-8 rounded-full bg-gradient-to-br from-slate-600 to-slate-700 border border-slate-500 flex items-center justify-center text-xs text-white font-bold uppercase shadow-inner">
                  {{ history.issueAssignee?.name?.charAt(0) || '🤖' }}
                </div>
                <div class="text-xs">
                  <p class="text-slate-200 font-semibold">{{ history.issueAssignee?.name || 'Système / Non assigné' }}</p>
                  <p class="text-slate-500">{{ history.issueAssignee?.email || 'Aucun email' }}</p>
                </div>
              </div>

            </div>
          </li>
        } @empty {
          <div class="flex flex-col items-center justify-center py-12 px-4 bg-slate-800/20 rounded-2xl border-2 border-dashed border-slate-700">
            <span class="text-3xl mb-3">📭</span>
            <p class="text-slate-300 font-medium text-sm">No history events found</p>
            <p class="text-slate-500 text-xs mt-1 text-center">Try adjusting your date range or project filters.</p>
          </div>
        }
      </ul>

      @if (historyPage.content && historyPage.content.length > 0) {
        <div class="mt-8 pt-6 border-t border-slate-700/50 flex flex-wrap items-center justify-between gap-4">

          <div class="flex items-center gap-2">
            <label class="text-xs font-semibold text-slate-400 uppercase tracking-wider">Items per page:</label>
            <select (change)="onSizeChange($event)"
                    class="bg-slate-900 border border-slate-700 rounded-lg px-2 py-1.5 text-xs text-slate-200 focus:border-blue-500 focus:outline-none transition-colors">
              <option [value]="5" [selected]="historyPage.size === 5">5</option>
              <option [value]="10" [selected]="historyPage.size === 10">10</option>
              <option [value]="20" [selected]="historyPage.size === 20">20</option>
            </select>
          </div>

          <div class="text-xs text-slate-400">
            Page <span class="font-bold text-slate-200">{{ historyPage.number + 1 }}</span> of <span class="font-bold text-slate-200">{{ historyPage.totalPages }}</span>
            <span class="mx-2 text-slate-600">|</span>
            Total: <span class="font-bold text-slate-200">{{ historyPage.totalElements }}</span>
          </div>

          <div class="flex items-center gap-2">
            <button (click)="onPageChange(historyPage.number - 1)"
                    [disabled]="historyPage.number === 0"
                    class="px-3 py-1.5 text-xs font-medium rounded-lg border border-slate-700 bg-slate-800 text-slate-300 hover:bg-slate-700 hover:text-white disabled:opacity-40 disabled:cursor-not-allowed transition-all shadow-sm">
              Previous
            </button>
            <button (click)="onPageChange(historyPage.number + 1)"
                    [disabled]="historyPage.number >= historyPage.totalPages - 1"
                    class="px-3 py-1.5 text-xs font-medium rounded-lg border border-slate-700 bg-slate-800 text-slate-300 hover:bg-slate-700 hover:text-white disabled:opacity-40 disabled:cursor-not-allowed transition-all shadow-sm">
              Next
            </button>
          </div>

        </div>
      }
    </div>
  </div>
}
